### ISSUE TITLE
Add Support For SFSymbols 5.0 and above

### ISSUE THREAD

**Issue by mergesort** [Rspoon3/SFSymbols#8]
Hi @Rspoon3, I was just wondering if you're planning on adding support for more recent SF Symbols, ones that were introduced in iOS 17 and above. I plan on adding them to my project but it's not time-sensitive, so if you don't I may add them in my fork in a few months, but either way I would love to see them.

Thanks a lot for the library and accepting my previous pull request, I really appreciate all the hard work!

**Comment by Rspoon3** [comment]
Hi @mergesort , version 2.5 should have all of the latest symbols. Go ahead and give it a try and let me know if any are missing.

**Comment by mergesort** [comment]
Thank you so much @Rspoon3!

**Comment by Nirma** [comment]
@Rspoon3 Cool project! I saw it as I was looking for my project on the Swift Package Index.

I was surprised because this project uses the same exact tagline as mine so I thought I already added it but the username was different, it might be a bit confusing to copy the tag line as well.
Thanks for the mention in the readme!

While I am here @mergesort if you are interested `SFSymbols6` through `SFSymbols1` have symbols based on version with previews of the symbol in the doc comments like this:
![demo6](https://github.com/user-attachments/assets/8a62cf63-6b73-4b0c-9d0d-db6ec01cde03)

https://github.com/Nirma/SFSymbol

@Rspoon3 Maybe adding that to this project too would be a nice improvement?

**Comment by Rspoon3** [comment]
I have just released version 2.6 that has all the symbols up to the latest SFSymbols release (6.0).

@Nirma Thats a good suggestion. I would like to have better documentation including a preview symbol at some point. If you feel strongly about it, please open a new issue to help me track it. For now, I’m going to close this thread as the work to update the symbols is now done.
